// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

/// <summary>
/// الفروع
/// </summary>
public partial class BranchesTb
{
    /// <summary>
    /// رقم الفرع
    /// </summary>
    public int BranchId { get; set; }

    /// <summary>
    /// اسم الفرع
    /// </summary>
    public string BranchName { get; set; }

    /// <summary>
    /// رقم الدولة
    /// </summary>
    public int CountryId { get; set; }

    /// <summary>
    /// رقم المحافظة
    /// </summary>
    public int StateId { get; set; }

    /// <summary>
    /// رقم المدينة
    /// </summary>
    public int CityId { get; set; }

    /// <summary>
    /// العنوان
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// رمز الفرع لدى سلطة النقد
    /// </summary>
    public string PmaBranchCode { get; set; }

    /// <summary>
    /// هل هذا الفرع فرع الإدارة العامة
    /// 0 = NO
    /// 1 = YES
    /// </summary>
    public bool? IsCentralFlag { get; set; }

    /// <summary>
    /// التاريخ الحالي للنظام
    /// </summary>
    public DateTime? CurrDate { get; set; }

    /// <summary>
    /// التاريخ السابق للنظام
    /// </summary>
    public DateTime? PrevDate { get; set; }

    /// <summary>
    /// هل الفرع في حال إغلاق يومي
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? DailyCloseFlag { get; set; }

    /// <summary>
    /// تاريخ ووقت بدء الإغلاق اليومي
    /// </summary>
    public DateTime? DailyCloseStartTime { get; set; }

    /// <summary>
    /// هل الفرع مغلق
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? CloseFlag { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    /// <summary>
    /// هل السجل مخفي فلا يظهر في قوائم الإدخال و التعديل
    /// 0 = غير مخفي
    /// 1 = مخفي
    /// </summary>
    public bool? IsHidden { get; set; }

    /// <summary>
    /// المحافظة
    /// </summary>
    public int? GovernorateId { get; set; }

    public virtual ICollection<ProfilesTb> ProfilesTbs { get; set; } = new List<ProfilesTb>();
}