// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

/// <summary>
/// الفروع
/// </summary>
public partial class BranchLangsTb
{
    /// <summary>
    /// رقم الفرع
    /// </summary>
    public int BranchId { get; set; }

    /// <summary>
    /// رمز اللغة
    /// AR,EN,FR,....
    /// </summary>
    public string LangId { get; set; }

    /// <summary>
    /// اسم الفرع
    /// </summary>
    public string BranchName { get; set; }

    /// <summary>
    /// العنوان
    /// </summary>
    public string Address { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }
}