// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

public partial class ProfileBankInformationTb
{
    public int ProfileId { get; set; }

    public int BankId { get; set; }

    public int? BankBranchId { get; set; }

    public string BankAccountNo { get; set; }

    public string Iban { get; set; }

    public byte? NumberOfYears { get; set; }

    public bool? TransferFlag { get; set; }

    public bool? LoanFlag { get; set; }

    public DateTime? AccountOpenDate { get; set; }

    public int? AccountTypeId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    /// <summary>
    /// رمز العملة للحساب
    /// </summary>
    public byte AccountCurrId { get; set; }

    public virtual ProfilesTb Profile { get; set; }
}