// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

public partial class ProfilesPartnersTb
{
    /// <summary>
    /// رقم الشريك
    /// </summary>
    public int PartnerId { get; set; }

    /// <summary>
    /// رقم الملف
    /// </summary>
    public int ProfileId { get; set; }

    /// <summary>
    /// نوع الشريك
    /// </summary>
    public bool? CustTypeId { get; set; }

    /// <summary>
    /// اسم الشريك الرباعي
    /// </summary>
    public string PartnerFullName { get; set; }

    /// <summary>
    /// نوع وثيقة التعريف
    /// 1 = هوية
    /// 2= VAT NUMBER مشتغل مرخص
    /// 3= جواز سفر فلسطيني
    /// 4 = جواز سفر أردني
    /// .....
    /// </summary>
    public int IdTypeId { get; set; }

    /// <summary>
    /// رقم وثيقة التعريف
    /// </summary>
    public string IdNum { get; set; }

    /// <summary>
    /// مكان الميلاد
    /// </summary>
    public string BirthPlace { get; set; }

    /// <summary>
    /// تاريخ الميلاد
    /// </summary>
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// الجنس
    /// </summary>
    public bool? GenderId { get; set; }

    /// <summary>
    /// الحالة الإجتماعية
    /// </summary>
    public byte? MaritalStatusId { get; set; }

    /// <summary>
    /// عدد المعالين 
    /// </summary>
    public byte? DependentsCnt { get; set; }

    /// <summary>
    /// عدد الأسهم
    /// </summary>
    public int SharesCnt { get; set; }

    /// <summary>
    /// نسبة المساهمة
    /// </summary>
    public decimal ContributionPercent { get; set; }

    /// <summary>
    /// مقترض قائم نعم =  2
    /// لا = 1
    /// </summary>
    public bool IsBankBorrower { get; set; }

    /// <summary>
    /// المؤهل العلمي
    /// </summary>
    public int? EducationLevelId { get; set; }

    /// <summary>
    /// سنوات الخبرة للعمل الحالي
    /// </summary>
    public int? ExperienceYearsCnt { get; set; }

    /// <summary>
    /// الدولة
    /// </summary>
    public int? CountryId { get; set; }

    /// <summary>
    /// المحافظة
    /// </summary>
    public int? StateId { get; set; }

    /// <summary>
    /// المدينة
    /// </summary>
    public int? CityId { get; set; }

    /// <summary>
    /// رقم الهاتف الارضي
    /// </summary>
    public string PhoneNumber { get; set; }

    /// <summary>
    /// رقم الهاتف المتنقل
    /// </summary>
    public string CelularNumber { get; set; }

    /// <summary>
    /// البريد الالكتروني
    /// </summary>
    public string Email { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    /// <summary>
    /// الحالة
    /// فعال=0
    /// غير فعال=1
    /// </summary>
    public bool? IsHidden { get; set; }

    /// <summary>
    /// الاسم الشخصي باللغة المحلية
    /// </summary>
    public string FirstNameNa { get; set; }

    /// <summary>
    /// اسم الأب باللغة المحلية
    /// </summary>
    public string FatherNameNa { get; set; }

    /// <summary>
    /// اسم الجد باللغة المحلية
    /// </summary>
    public string GrandFatherNameNa { get; set; }

    /// <summary>
    /// اسم العائلة باللغة المحلية
    /// </summary>
    public string FamilyNameNa { get; set; }

    /// <summary>
    /// تفاصيل الخبرة للعمل الحالي
    /// </summary>
    public string CurrentExperienceNotes { get; set; }

    /// <summary>
    /// ملاحظات
    /// </summary>
    public string Notes { get; set; }

    /// <summary>
    /// الخبرة في مجالات اخرى
    /// </summary>
    public string OtherExperienceNotes { get; set; }

    /// <summary>
    /// ملاحظات حول الشركة التابعة 
    /// </summary>
    public string CompanyNotes { get; set; }

    /// <summary>
    /// العنوان
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// العميل:
    /// 1- مقيم
    /// 2- غير مقيم
    /// </summary>
    public bool? ResidentFlag { get; set; }

    public virtual ProfilesTb Profile { get; set; }
}