// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

/// <summary>
/// الملفات - بيانات العمل
/// </summary>
public partial class ProfileWorksTb
{
    /// <summary>
    /// SERIAL
    /// </summary>
    public int WorkId { get; set; }

    /// <summary>
    /// رقم العميل
    /// SERIAL
    /// </summary>
    public int ProfileId { get; set; }

    /// <summary>
    /// طبيعة العمل
    /// </summary>
    public int? WorkNatureId { get; set; }

    /// <summary>
    /// المهنة
    /// </summary>
    public int? JobId { get; set; }

    /// <summary>
    /// مكان العمل
    /// </summary>
    public string WorkPlace { get; set; }

    /// <summary>
    /// الراتب
    /// </summary>
    public decimal? Salary { get; set; }

    /// <summary>
    /// العملة
    /// </summary>
    public byte? CurrId { get; set; }

    /// <summary>
    /// مدة أساس احتساب الراتب 
    /// 1   سنوي
    /// 2   شهري 
    /// 3   أسبوعي 
    /// 4   يومي 
    /// 5   ساعة 
    /// </summary>
    public int? SalaryPeriodId { get; set; }

    /// <summary>
    /// سنوات الخدمة
    /// </summary>
    public byte? WorkingYears { get; set; }

    /// <summary>
    /// رقم الدولة
    /// </summary>
    public int? CountryId { get; set; }

    /// <summary>
    /// المحافظة
    /// </summary>
    public int? StateId { get; set; }

    /// <summary>
    /// رقم المدينة
    /// </summary>
    public int? CityId { get; set; }

    /// <summary>
    /// العنوان
    /// 
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// هاتف
    /// </summary>
    public string Tel { get; set; }

    /// <summary>
    /// هل له راتب محول للبنك
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? BankSalaryFlag { get; set; }

    /// <summary>
    /// رقم البنك
    /// </summary>
    public int? BankId { get; set; }

    /// <summary>
    /// رقم الفرع
    /// </summary>
    public int? BankBranchId { get; set; }

    /// <summary>
    /// رقم الحساب البنكي
    /// 
    /// </summary>
    public string BankAccountNo { get; set; }

    /// <summary>
    /// رقم الIBAN
    /// </summary>
    public string Iban { get; set; }

    /// <summary>
    /// عدد سنوات التعامل مع البنك
    /// </summary>
    public byte? BankYears { get; set; }

    /// <summary>
    /// هل حصلت على تمويلات او قروض
    /// </summary>
    public bool? BankLoanFlag { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    /// <summary>
    /// رقم البناية
    /// </summary>
    public string BuildingNo { get; set; }

    /// <summary>
    /// رقم المكتب
    /// </summary>
    public string OfficeNo { get; set; }

    public virtual ProfilesTb Profile { get; set; }
}