// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProfileMigration.DAL.Models;

/// <summary>
/// الملفات
/// الشركات، الأفراد ، العملاء،  الزوجات، الكفلاء...
/// </summary>
public partial class ProfilesTb
{
    /// <summary>
    /// رقم الملف
    /// </summary>
    public int ProfileId { get; set; }

    /// <summary>
    /// رقم الفرع
    /// </summary>
    public int? BranchId { get; set; }

    /// <summary>
    /// رقم العميل
    /// SERIAL
    /// </summary>
    public long? CustId { get; set; }

    /// <summary>
    /// نوع وثيقة التعريف
    /// 1 = هوية
    /// 2= VAT NUMBER مشتغل مرخص
    /// 3= جواز سفر فلسطيني
    /// 4 = جواز سفر أردني
    /// .....
    /// </summary>
    public int? IdTypeId { get; set; }

    /// <summary>
    /// رقم وثيقة التعريف
    /// </summary>
    public string IdNum { get; set; }

    /// <summary>
    /// تاريخ الإصدار
    /// </summary>
    public DateTime? IssueDate { get; set; }

    /// <summary>
    /// تاريخ الإنتهاء
    /// </summary>
    public DateTime? ExpiryDate { get; set; }

    /// <summary>
    /// مكان الإصدار
    /// </summary>
    public string IssuePlace { get; set; }

    /// <summary>
    /// اسم صاحب الملف
    /// </summary>
    public string ProfileNameNa { get; set; }

    /// <summary>
    /// اسم صاحب الملف
    /// </summary>
    public string ProfileNameFo { get; set; }

    /// <summary>
    /// نوع العميل
    /// 1=FIRM
    /// 2=INDIVIDUAL
    /// 
    /// </summary>
    public bool CustTypeId { get; set; }

    /// <summary>
    /// الاسم الشخصي باللغة المحلية
    /// </summary>
    public string FirstNameNa { get; set; }

    /// <summary>
    /// اسم الأب باللغة المحلية
    /// </summary>
    public string FatherNameNa { get; set; }

    /// <summary>
    /// اسم الجد باللغة المحلية
    /// </summary>
    public string GrandFatherNameNa { get; set; }

    /// <summary>
    /// اسم العائلة باللغة المحلية
    /// </summary>
    public string FamilyNameNa { get; set; }

    /// <summary>
    /// الاسم الشخصي باللغة الأجنبية
    /// </summary>
    public string FirstNameFo { get; set; }

    /// <summary>
    /// اسم الأب باللغة الأجنبية
    /// </summary>
    public string FatherNameFo { get; set; }

    /// <summary>
    /// اسم الجد باللغة الأجنبية
    /// </summary>
    public string GrandFatherNameFo { get; set; }

    /// <summary>
    /// اسم العائلة باللغة الأجنبية
    /// </summary>
    public string FamilyNameFo { get; set; }

    /// <summary>
    /// الاسم المختصر للعميل باللغة المحلية
    /// </summary>
    public string ShortName { get; set; }

    /// <summary>
    /// اللقب
    /// </summary>
    public int? TitleId { get; set; }

    /// <summary>
    /// الكنية - اسم الشهرة
    /// </summary>
    public string NickName { get; set; }

    /// <summary>
    /// اسم الام
    /// </summary>
    public string MotherName { get; set; }

    /// <summary>
    /// تاريخ الميلاد
    /// </summary>
    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// مكان الميلاد
    /// </summary>
    public string BirthPlace { get; set; }

    /// <summary>
    /// الجنس
    /// </summary>
    public bool? GenderId { get; set; }

    /// <summary>
    /// الحالة الإجتماعية
    /// </summary>
    public byte? MaritalStatusId { get; set; }

    /// <summary>
    /// المستوى التعليمي
    /// </summary>
    public int? EducationLevelId { get; set; }

    /// <summary>
    /// إرسال كشف الحساب
    /// 0 = بدون إرسال
    /// 1= شهري MONTHLY
    /// 2 = ربع سنوي QUARTERLY YEARLY
    /// 3 = نص سنوي HALF YEARLY
    /// 4 = سنوي YEARLY 
    /// </summary>
    public byte? SendAccountStatementId { get; set; }

    /// <summary>
    /// عدد الاولاد الكلي
    /// </summary>
    public byte? ChildrenCnt { get; set; }

    /// <summary>
    /// عدد الأولاد تحت سن 18 سنة 
    /// </summary>
    public byte? ChildrenUnderEightteenCnt { get; set; }

    /// <summary>
    /// عدد المعالين 
    /// </summary>
    public byte? DependentsCnt { get; set; }

    /// <summary>
    /// عدد الذكور (المعالين)
    /// </summary>
    public byte? DependentsMalesCnt { get; set; }

    /// <summary>
    /// عدد الإناث (المعالين)
    /// </summary>
    public byte? DependentsFemalesCnt { get; set; }

    /// <summary>
    /// هل يوجد أحد من أفراد الأسرة لديه مرض مزمن أو إعاقة
    /// 0 = no
    /// 1 = yes
    /// </summary>
    public bool? ChronicFlag { get; set; }

    /// <summary>
    /// وصف الإعاقة أو الأمراض المزمنة
    /// </summary>
    public string ChronicDetails { get; set; }

    /// <summary>
    /// عدد افراد الأسرة
    /// </summary>
    public byte? FamilyMembersCnt { get; set; }

    /// <summary>
    /// عدد العاملين من الأهل(الأب والام)
    /// </summary>
    public byte? ParentsWorkCnt { get; set; }

    /// <summary>
    /// عدد غير العاملين من الأهل(الأب والام)
    /// </summary>
    public byte? ParentsNoWorkCnt { get; set; }

    /// <summary>
    /// عدد العاملين من الأخوة والأخوات
    /// </summary>
    public byte? BrothersWorkCnt { get; set; }

    /// <summary>
    /// عدد غير العاملين من الأخوة والأخوات
    /// </summary>
    public byte? BrothersNoWorkCnt { get; set; }

    /// <summary>
    /// عدد العاملين من الزوج/الزوجة
    /// </summary>
    public byte? SpouseWorkCnt { get; set; }

    /// <summary>
    /// عدد غير العاملين من الزوج/الزوجة
    /// </summary>
    public byte? SpouseNoWorkCnt { get; set; }

    /// <summary>
    /// عدد العاملين من الأبناء
    /// </summary>
    public byte? ChildrenWorkCnt { get; set; }

    /// <summary>
    /// عدد غير العاملين من الأبناء
    /// </summary>
    public byte? ChildrenNoWorkCnt { get; set; }

    /// <summary>
    /// الوزن
    /// </summary>
    public byte? Weight { get; set; }

    /// <summary>
    /// الطول
    /// </summary>
    public byte? Hight { get; set; }

    /// <summary>
    /// الاسم التجاري
    /// </summary>
    public string CommercialName { get; set; }

    /// <summary>
    /// اسم المجموعة
    /// </summary>
    public string GroupName { get; set; }

    /// <summary>
    /// الرقم الضريبي
    /// </summary>
    public string VatNum { get; set; }

    /// <summary>
    /// رأس المال
    /// 
    /// </summary>
    public decimal? Capital { get; set; }

    /// <summary>
    /// العملة
    /// </summary>
    public byte? CurrId { get; set; }

    /// <summary>
    /// عدد الموظفين
    /// </summary>
    public int? NumberOfEmployees { get; set; }

    /// <summary>
    /// عدد الفروع
    /// </summary>
    public int? NumberOfBranches { get; set; }

    /// <summary>
    /// عدد المركبات
    /// </summary>
    public int? NumberOfVehicles { get; set; }

    /// <summary>
    /// تاريخ التأسيس
    /// </summary>
    public DateTime? IstablishmentDate { get; set; }

    /// <summary>
    /// الحالة : و تمثل عدد مرات الإضافة على القائمة مطروحاً منها عدد مرات الإلغاء
    /// يتم تعديل بيانات السجل وكذلك العميل لنفس الحقل بناءً على رقم العميل
    /// 0= تم إضافته و إلغاؤه أي خرج من القائمة السوداء
    /// &gt;0 مازال على القئمة السوداء
    /// </summary>
    public int? BlackListCount { get; set; }

    /// <summary>
    /// حد الدين
    /// </summary>
    public decimal? DebtLimitValue { get; set; }

    /// <summary>
    /// نوع مدة حد الدين
    /// 2=شهر
    /// </summary>
    public int? DebtLimitPeriodId { get; set; }

    /// <summary>
    /// مدة حد الدين بالأشهر
    /// </summary>
    public int? DebtLimitDuration { get; set; }

    /// <summary>
    /// الحد الأقصى للشيكات رسم التحصيل (العملة الافتراضية للنظام)
    /// </summary>
    public decimal? MaxCollectionChecksValue { get; set; }

    /// <summary>
    /// مدير الحساب
    /// </summary>
    public int? AccountManagerUserId { get; set; }

    /// <summary>
    /// هل عليه لتسهيلات خارجية
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? HasExtFacilitiesFlag { get; set; }

    /// <summary>
    /// القسط الشهري للتسهيلات الخارجية
    /// </summary>
    public decimal? ExtFacilitiesMonthlyInst { get; set; }

    /// <summary>
    /// عملة التسهيلات الخارجية
    /// </summary>
    public byte? ExtFacilitiesCurrId { get; set; }

    /// <summary>
    /// هل عليه كفالات خارجية
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? HasExtGuaranteesFlag { get; set; }

    /// <summary>
    /// القسط الشهري للكفالات الخارجية
    /// </summary>
    public decimal? ExtGuaranteesMonthlyInst { get; set; }

    /// <summary>
    /// عملة الكفالات الخارجية
    /// </summary>
    public byte? ExtGuaranteesCurrId { get; set; }

    /// <summary>
    /// القطاع
    /// 1 = خاص 
    /// 2 = حكومي
    /// </summary>
    public int? SectorId { get; set; }

    /// <summary>
    /// النشاط الاقتصادي
    /// </summary>
    public int? EconomicActivityId { get; set; }

    /// <summary>
    /// نوع النشاط
    /// </summary>
    public int? ActivityId { get; set; }

    /// <summary>
    /// الشكل القانوني
    /// </summary>
    public int? FirmLegalTypeId { get; set; }

    /// <summary>
    /// نوع المؤسسة
    /// </summary>
    public int? FirmTypeId { get; set; }

    /// <summary>
    /// تصنيف العميل
    /// </summary>
    public int? ClassId { get; set; }

    /// <summary>
    /// رقم التصنيف  المالي للعميل  
    /// </summary>
    public int? FinancialClassId { get; set; }

    /// <summary>
    /// النشاط
    /// </summary>
    public string ActivityName { get; set; }

    /// <summary>
    /// العملة
    /// </summary>
    public byte? IncomeCurrId { get; set; }

    /// <summary>
    /// القيمة
    /// </summary>
    public decimal? IncomeAmount { get; set; }

    /// <summary>
    /// الاسم مفلتر
    /// </summary>
    public string ProfileNameFNa { get; set; }

    /// <summary>
    /// الاسم مفلتر
    /// </summary>
    public string ProfileNameFFo { get; set; }

    /// <summary>
    /// مقيم
    /// 0 = غير مقيم
    /// 1 = مقيم
    /// </summary>
    public bool? ResidentFlag { get; set; }

    /// <summary>
    /// مصدر إدخال البيانات
    /// 1 = الشركة
    /// 2 = الشخص نفسه
    /// </summary>
    public bool? EntrySourceId { get; set; }

    /// <summary>
    /// هل تمت مراجعة البيانات من قبل الشركة
    /// 0 = لا
    /// 1 = نعم
    /// </summary>
    public bool? ReviewFlag { get; set; }

    /// <summary>
    /// هل العميل من ذوي الاحتياجات الخاصة او لديه مرض مزمن؟
    /// 1 = yes
    /// 0 = no
    /// </summary>
    public bool? SpecialNeedsFlag { get; set; }

    /// <summary>
    /// الجهة المشغلة - صاحب العمل
    /// </summary>
    public int? EmployerId { get; set; }

    /// <summary>
    /// حالة العميل
    /// 1 = فعال
    /// 0 = غير فعال
    /// </summary>
    public bool? CustStatusId { get; set; }

    public DateTime? StatusUpdatedOn { get; set; }

    public int? StatusUpdatedBy { get; set; }

    /// <summary>
    /// العنوان الحالي - الدولة
    /// للشركات = عنوان المركز الرئيسي
    /// </summary>
    public int? CurrCountryId { get; set; }

    /// <summary>
    /// العنوان الحالي -  المحافظة
    /// للشركات = عنوان المركز الرئيسي
    /// </summary>
    public int? CurrStateId { get; set; }

    /// <summary>
    /// العنوان الحالي - المدينة
    /// للشركات = عنوان المركز الرئيسي
    /// </summary>
    public int? CurrCityId { get; set; }

    /// <summary>
    /// العنوان الحالي - العنوان
    /// للشركات = عنوان المركز الرئيسي
    /// </summary>
    public string CurrAddress { get; set; }

    /// <summary>
    /// العنوان الحالي - ملكية السكن
    /// للأفراد فقط
    /// </summary>
    public bool? CurrHomeOwnershipId { get; set; }

    /// <summary>
    /// اعتماد بيانات العنوان الدائم نفس بيانات العنوان الحالي
    /// 1 = YES
    /// 0 = NO
    /// </summary>
    public bool? PermanentAddressFlag { get; set; }

    /// <summary>
    /// العنوان الدائم -  الدولة
    /// للشركات = عنوان مزاولة العمل
    /// </summary>
    public int? PermanentCountryId { get; set; }

    /// <summary>
    /// العنوان الدائم - المحافظة
    /// للشركات = عنوان مزاولة العمل
    /// </summary>
    public int? PermanentStateId { get; set; }

    /// <summary>
    /// العنوان الدائم -  المدينة
    /// للشركات = عنوان مزاولة العمل
    /// </summary>
    public int? PermanentCityId { get; set; }

    /// <summary>
    /// العنوان الدائم - العنوان
    /// للشركات = عنوان مزاولة العمل
    /// </summary>
    public string PermanentAddress { get; set; }

    /// <summary>
    /// العنوان الدائم - ملكية السكن
    /// للافراد فقط
    /// </summary>
    public bool? PermanentHomeOwnershipId { get; set; }

    /// <summary>
    /// اعتماد بيانات المراسلة نفس بيانات العنوان الحالي
    /// 1 = YES
    /// 0 = NO
    /// </summary>
    public bool? MailAddressFlag { get; set; }

    /// <summary>
    /// عنوان المراسلة - الدولة
    /// </summary>
    public int? MailCountryId { get; set; }

    /// <summary>
    /// عنوان المراسلة - المحافظة
    /// </summary>
    public int? MailStateId { get; set; }

    /// <summary>
    /// عنوان المراسلة -  المدينة
    /// </summary>
    public int? MailCityId { get; set; }

    /// <summary>
    /// عنوان المراسلة - العنوان
    /// </summary>
    public string MailAddress { get; set; }

    /// <summary>
    /// لغة المراسلة
    /// AR,EN,FR,....
    /// </summary>
    public string MailLangId { get; set; }

    /// <summary>
    /// رقم بريد المراسلة
    /// </summary>
    public string MailPobox { get; set; }

    /// <summary>
    /// الرمز البريدي
    /// </summary>
    public string MailZip { get; set; }

    /// <summary>
    /// رقم الفاكس
    /// 
    /// </summary>
    public string MailFax { get; set; }

    /// <summary>
    /// رقم التلكس
    /// 
    /// </summary>
    public string MailTelex { get; set; }

    /// <summary>
    ///  اسم رئيس الهيئة
    /// </summary>
    public string ChairmanName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? UpdatedBy { get; set; }

    /// <summary>
    /// رقم المجموعة
    /// </summary>
    public int? GroupId { get; set; }

    /// <summary>
    /// معدل المبيعات سنويا
    /// </summary>
    public decimal? AnnualSalesRate { get; set; }

    /// <summary>
    /// عملة معدل المبيعات
    /// </summary>
    public byte? AnnualSalesRateCurrId { get; set; }

    /// <summary>
    /// هل البروفايل لعميل
    /// 0=لا
    /// 1=نعم
    /// </summary>
    public bool? IsCustomer { get; set; }

    /// <summary>
    /// هل بيانات العميل مكتملة 
    /// 0=لا 
    /// 1=نعم
    /// </summary>
    public bool? IsCompleated { get; set; }

    /// <summary>
    /// تاريخ الموافقة
    /// </summary>
    public DateTime? CustApprovedOn { get; set; }

    /// <summary>
    /// الموافقة بواسطة
    /// </summary>
    public int? CustApprovedBy { get; set; }

    /// <summary>
    /// رأس المال المصرح به و المدفوع
    /// </summary>
    public decimal? CapitalAuthorizedPaid { get; set; }

    /// <summary>
    /// تاريخ ممارسة النشاط الفعلي
    /// </summary>
    public DateTime? ActualActivityDate { get; set; }

    /// <summary>
    /// جهة الإصدار لشهادة التسجيل
    /// </summary>
    public int? IssuerCertificateRegisterId { get; set; }

    /// <summary>
    /// نوع الاقامة في فلسطين محلية أو أجنبية
    /// </summary>
    public int? AccommodationTypeId { get; set; }

    /// <summary>
    /// مكان إصدار الوثيقة من المحافظات الفلسطينية
    /// </summary>
    public int? IssuePlaceId { get; set; }

    /// <summary>
    /// هل معرض للخطر
    /// 1 نعم
    /// 0 لا
    /// </summary>
    public bool? IsInRisk { get; set; }

    /// <summary>
    /// نوع الخطر (عالي، متوسط، منخفض)
    /// </summary>
    public int? RiskTypeId { get; set; }

    /// <summary>
    /// المنصب
    /// </summary>
    public int? PositionId { get; set; }

    /// <summary>
    /// مسمى المنصب
    /// </summary>
    public string PositionTitle { get; set; }

    /// <summary>
    /// تاريخ انتهاء صلاحية البيانات وتحدد من الاعدادت حسب اخر تعديل على بيانات الحساب
    /// </summary>
    public DateTime? DataExpiryDate { get; set; }

    /// <summary>
    /// عدد العاملين الذكور
    /// </summary>
    public int? EmployeesMaleCnt { get; set; }

    /// <summary>
    /// عدد العاملين الاناث
    /// </summary>
    public int? EmployeesFemaleCnt { get; set; }

    /// <summary>
    /// تاريخ اخر اصدار لشهادة التسجيل
    /// </summary>
    public DateTime? LatestRegCirtificate { get; set; }

    /// <summary>
    /// هل بيانات العميل بالنسبة للبورتال مكتملة
    /// 0 لا
    /// 1 نعم
    /// </summary>
    public bool? IsPortalCompleated { get; set; }

    /// <summary>
    /// هل لديه اعضاء مجلس ادارة
    /// 0 لا
    /// 1 نعم
    /// </summary>
    public bool? HasBoardMembersFlag { get; set; }

    /// <summary>
    /// هل لديه منافسين
    /// 0 لا
    /// 1 نعم
    /// </summary>
    public bool? HasCompetitorsFlag { get; set; }

    /// <summary>
    /// ملاحظات
    /// </summary>
    public string Notes { get; set; }

    /// <summary>
    /// تاريخ الوفاة
    /// </summary>
    public DateTime? DeathDate { get; set; }

    /// <summary>
    /// له أقارب سياسيون
    ///  0 لا
    ///  1 نعم
    /// </summary>
    public bool? HasPoliticalRelativesFlag { get; set; }

    /// <summary>
    /// يرسل كشف حساب عبر 
    ///  
    /// رقم 114 في الثوابت
    /// </summary>
    public byte? SendAccountStatementViaId { get; set; }

    /// <summary>
    /// هل يعتبر أحد المالكين، المفوضين بالتوقيع، المدراء التنفيذيين من المتنفذين السياسيين/ القضائيين/ العسكريين 
    ///  
    /// 1- نعم 
    /// 0- لا
    /// </summary>
    public bool? HasPoliticalOwnersFlag { get; set; }

    /// <summary>
    /// القطاع الإقتصادي
    /// 
    /// رقم 148 في جدول الثوابت
    /// </summary>
    public int? EconomicSectorId { get; set; }

    public virtual BranchesTb Branch { get; set; }

    public virtual ICollection<ProfileBankInformationTb> ProfileBankInformationTbs { get; set; } = new List<ProfileBankInformationTb>();

    public virtual ICollection<ProfileWorksTb> ProfileWorksTbs { get; set; } = new List<ProfileWorksTb>();

    public virtual ICollection<ProfilesPartnersTb> ProfilesPartnersTbs { get; set; } = new List<ProfilesPartnersTb>();
}