// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProfileMigration.DAL.Models;

public partial class SilaDbContext : DbContext
{
    public SilaDbContext(DbContextOptions<SilaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BranchLangsTb> BranchLangsTbs { get; set; }

    public virtual DbSet<BranchesTb> BranchesTbs { get; set; }

    public virtual DbSet<CConstantLangsTb> CConstantLangsTbs { get; set; }

    public virtual DbSet<CConstantsTb> CConstantsTbs { get; set; }

    public virtual DbSet<ProfileContactDtsTb> ProfileContactDtsTbs { get; set; }

    public virtual DbSet<ProfileBankInformationTb> ProfileBankInformationTbs { get; set; }

    public virtual DbSet<ProfileWorksTb> ProfileWorksTbs { get; set; }

    public virtual DbSet<ProfilesPartnersTb> ProfilesPartnersTbs { get; set; }

    public virtual DbSet<ProfilesTb> ProfilesTbs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("RHODES_BANKING_SILA")
            .UseCollation("USING_NLS_COMP");

        modelBuilder.Entity<BranchLangsTb>(entity =>
        {
            entity.HasKey(e => new { e.BranchId, e.LangId }).HasName("BRANCH_LANGS_PK");

            entity.ToTable("BRANCH_LANGS_TB", tb => tb.HasComment("الفروع"));

            entity.Property(e => e.BranchId)
                .HasPrecision(9)
                .HasComment("رقم الفرع")
                .HasColumnName("BRANCH_ID");
            entity.Property(e => e.LangId)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasComment("رمز اللغة\nAR,EN,FR,....")
                .HasColumnName("LANG_ID");
            entity.Property(e => e.Address)
                .HasMaxLength(300)
                .HasComment("العنوان")
                .HasColumnName("ADDRESS");
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("اسم الفرع")
                .HasColumnName("BRANCH_NAME");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<BranchesTb>(entity =>
        {
            entity.HasKey(e => e.BranchId).HasName("BRANCHES_PK");

            entity.ToTable("BRANCHES_TB", tb => tb.HasComment("الفروع"));

            entity.Property(e => e.BranchId)
                .HasPrecision(9)
                .ValueGeneratedNever()
                .HasComment("رقم الفرع")
                .HasColumnName("BRANCH_ID");
            entity.Property(e => e.Address)
                .HasMaxLength(300)
                .HasComment("العنوان")
                .HasColumnName("ADDRESS");
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("اسم الفرع")
                .HasColumnName("BRANCH_NAME");
            entity.Property(e => e.CityId)
                .HasPrecision(9)
                .HasComment("رقم المدينة")
                .HasColumnName("CITY_ID");
            entity.Property(e => e.CloseFlag)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("هل الفرع مغلق\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CLOSE_FLAG");
            entity.Property(e => e.CountryId)
                .HasPrecision(9)
                .HasComment("رقم الدولة")
                .HasColumnName("COUNTRY_ID");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CurrDate)
                .HasComment("التاريخ الحالي للنظام")
                .HasColumnType("DATE")
                .HasColumnName("CURR_DATE");
            entity.Property(e => e.DailyCloseFlag)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("هل الفرع في حال إغلاق يومي\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("DAILY_CLOSE_FLAG");
            entity.Property(e => e.DailyCloseStartTime)
                .HasComment("تاريخ ووقت بدء الإغلاق اليومي")
                .HasColumnType("DATE")
                .HasColumnName("DAILY_CLOSE_START_TIME");
            entity.Property(e => e.GovernorateId)
                .HasPrecision(9)
                .HasComment("المحافظة")
                .HasColumnName("GOVERNORATE_ID");
            entity.Property(e => e.IsCentralFlag)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("هل هذا الفرع فرع الإدارة العامة\n0 = NO\n1 = YES")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_CENTRAL_FLAG");
            entity.Property(e => e.IsHidden)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("هل السجل مخفي فلا يظهر في قوائم الإدخال و التعديل\n0 = غير مخفي\n1 = مخفي")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_HIDDEN");
            entity.Property(e => e.PmaBranchCode)
                .HasMaxLength(50)
                .HasComment("رمز الفرع لدى سلطة النقد")
                .HasColumnName("PMA_BRANCH_CODE");
            entity.Property(e => e.PrevDate)
                .HasComment("التاريخ السابق للنظام")
                .HasColumnType("DATE")
                .HasColumnName("PREV_DATE");
            entity.Property(e => e.StateId)
                .HasPrecision(9)
                .HasComment("رقم المحافظة")
                .HasColumnName("STATE_ID");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<CConstantsTb>(entity =>
        {
            entity.HasKey(e => new { e.ConstantMainId, e.ConstantId }).HasName("C_CONSTANTS_PK");

            entity.ToTable("C_CONSTANTS_TB");

            entity.Property(e => e.ConstantMainId)
                .HasPrecision(9)
                .HasColumnName("CONSTANT_MAIN_ID");
            entity.Property(e => e.ConstantId)
                .HasPrecision(9)
                .HasColumnName("CONSTANT_ID");
            entity.Property(e => e.ConstantDesc)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_DESC");
            entity.Property(e => e.ParentConstantId)
                .HasPrecision(9)
                .HasColumnName("PARENT_CONSTANT_ID");
            entity.Property(e => e.PmaCode)
                .HasMaxLength(200)
                .HasColumnName("PMA_CODE");
            entity.Property(e => e.ConstantCondition)
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_CONDITION");
            entity.Property(e => e.ConstantCode1)
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_CODE1");
            entity.Property(e => e.ConstantCode2)
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_CODE2");
            entity.Property(e => e.ConstantCode3)
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_CODE3");
            entity.Property(e => e.IsUpdatable)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_UPDATABLE");
            entity.Property(e => e.IsHidden)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_HIDDEN");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
        });

        modelBuilder.Entity<CConstantLangsTb>(entity =>
        {
            entity.HasKey(e => new { e.ConstantMainId, e.ConstantId, e.LangId }).HasName("C_CONSTANT_LANGS_PK");

            entity.ToTable("C_CONSTANT_LANGS_TB");

            entity.Property(e => e.ConstantMainId)
                .HasPrecision(9)
                .HasColumnName("CONSTANT_MAIN_ID");
            entity.Property(e => e.ConstantId)
                .HasPrecision(9)
                .HasColumnName("CONSTANT_ID");
            entity.Property(e => e.LangId)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("LANG_ID");
            entity.Property(e => e.ConstantDesc)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("CONSTANT_DESC");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
        });

        modelBuilder.Entity<ProfileContactDtsTb>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("PROFILE_CONTACT_DTS_PK");

            entity.ToTable("PROFILE_CONTACT_DTS_TB");

            entity.Property(e => e.ContactId)
                .HasPrecision(9)
                .ValueGeneratedNever()
                .HasColumnName("CONTACT_ID");
            entity.Property(e => e.ProfileId)
                .HasPrecision(9)
                .HasColumnName("PROFILE_ID");
            entity.Property(e => e.ContactTypeId)
                .HasPrecision(9)
                .HasColumnName("CONTACT_TYPE_ID");
            entity.Property(e => e.ContactSubTypeId)
                .HasPrecision(9)
                .HasColumnName("CONTACT_SUB_TYPE_ID");
            entity.Property(e => e.ContactInfo)
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnName("CONTACT_INFO");
            entity.Property(e => e.ContactCountryId)
                .HasPrecision(9)
                .HasColumnName("CONTACT_COUNTRY_ID");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");

            entity.HasOne<ProfilesTb>()
                .WithMany()
                .HasForeignKey(d => d.ProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PROFILE_CONTACT_DTS_FK");
        });

        modelBuilder.Entity<ProfileBankInformationTb>(entity =>
        {
            entity.HasKey(e => new { e.ProfileId, e.BankId, e.Iban }).HasName("PROFILE_BANK_INFORMATION_PK");

            entity.ToTable("PROFILE_BANK_INFORMATION_TB");

            entity.HasIndex(e => e.Iban, "PROFILE_BANK_INFORMATION_I1");

            entity.Property(e => e.ProfileId)
                .HasPrecision(9)
                .HasColumnName("PROFILE_ID");
            entity.Property(e => e.BankId)
                .HasPrecision(9)
                .HasColumnName("BANK_ID");
            entity.Property(e => e.Iban)
                .HasMaxLength(1000)
                .HasColumnName("IBAN");
            entity.Property(e => e.AccountCurrId)
                .HasPrecision(3)
                .HasDefaultValueSql("NULL ")
                .HasComment("رمز العملة للحساب")
                .HasColumnName("ACCOUNT_CURR_ID");
            entity.Property(e => e.AccountOpenDate)
                .HasColumnType("DATE")
                .HasColumnName("ACCOUNT_OPEN_DATE");
            entity.Property(e => e.AccountTypeId)
                .HasPrecision(9)
                .HasColumnName("ACCOUNT_TYPE_ID");
            entity.Property(e => e.BankAccountNo)
                .HasMaxLength(50)
                .HasColumnName("BANK_ACCOUNT_NO");
            entity.Property(e => e.BankBranchId)
                .HasPrecision(9)
                .HasColumnName("BANK_BRANCH_ID");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.LoanFlag)
                .HasColumnType("NUMBER(1)")
                .HasColumnName("LOAN_FLAG");
            entity.Property(e => e.NumberOfYears)
                .HasPrecision(3)
                .HasColumnName("NUMBER_OF_YEARS");
            entity.Property(e => e.TransferFlag)
                .HasColumnType("NUMBER(1)")
                .HasColumnName("TRANSFER_FLAG");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Profile).WithMany(p => p.ProfileBankInformationTbs)
                .HasForeignKey(d => d.ProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PROFILE_BANK_INFORMATION_FK");
        });

        modelBuilder.Entity<ProfileWorksTb>(entity =>
        {
            entity.HasKey(e => e.WorkId).HasName("PROFILE_WORKS_PK");

            entity.ToTable("PROFILE_WORKS_TB", tb => tb.HasComment("الملفات - بيانات العمل"));

            entity.HasIndex(e => e.ProfileId, "PROFILE_WORKS_I1");

            entity.Property(e => e.WorkId)
                .HasPrecision(9)
                .ValueGeneratedNever()
                .HasComment("SERIAL")
                .HasColumnName("WORK_ID");
            entity.Property(e => e.Address)
                .HasMaxLength(300)
                .HasComment("العنوان\n")
                .HasColumnName("ADDRESS");
            entity.Property(e => e.BankAccountNo)
                .HasMaxLength(30)
                .HasComment("رقم الحساب البنكي\n")
                .HasColumnName("BANK_ACCOUNT_NO");
            entity.Property(e => e.BankBranchId)
                .HasPrecision(9)
                .HasComment("رقم الفرع")
                .HasColumnName("BANK_BRANCH_ID");
            entity.Property(e => e.BankId)
                .HasPrecision(9)
                .HasComment("رقم البنك")
                .HasColumnName("BANK_ID");
            entity.Property(e => e.BankLoanFlag)
                .HasComment("هل حصلت على تمويلات او قروض")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("BANK_LOAN_FLAG");
            entity.Property(e => e.BankSalaryFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل له راتب محول للبنك\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("BANK_SALARY_FLAG");
            entity.Property(e => e.BankYears)
                .HasPrecision(3)
                .HasComment("عدد سنوات التعامل مع البنك")
                .HasColumnName("BANK_YEARS");
            entity.Property(e => e.BuildingNo)
                .HasMaxLength(200)
                .HasComment("رقم البناية")
                .HasColumnName("BUILDING_NO");
            entity.Property(e => e.CityId)
                .HasPrecision(9)
                .HasComment("رقم المدينة")
                .HasColumnName("CITY_ID");
            entity.Property(e => e.CountryId)
                .HasPrecision(9)
                .HasComment("رقم الدولة")
                .HasColumnName("COUNTRY_ID");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CurrId)
                .HasPrecision(3)
                .HasComment("العملة")
                .HasColumnName("CURR_ID");
            entity.Property(e => e.Iban)
                .HasMaxLength(400)
                .HasComment("رقم الIBAN")
                .HasColumnName("IBAN");
            entity.Property(e => e.JobId)
                .HasPrecision(9)
                .HasComment("المهنة")
                .HasColumnName("JOB_ID");
            entity.Property(e => e.OfficeNo)
                .HasMaxLength(200)
                .HasComment("رقم المكتب")
                .HasColumnName("OFFICE_NO");
            entity.Property(e => e.ProfileId)
                .HasPrecision(9)
                .HasComment("رقم العميل\nSERIAL")
                .HasColumnName("PROFILE_ID");
            entity.Property(e => e.Salary)
                .HasComment("الراتب")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("SALARY");
            entity.Property(e => e.SalaryPeriodId)
                .HasPrecision(9)
                .HasComment("مدة أساس احتساب الراتب \n1   سنوي\n2   شهري \n3   أسبوعي \n4   يومي \n5   ساعة ")
                .HasColumnName("SALARY_PERIOD_ID");
            entity.Property(e => e.StateId)
                .HasPrecision(9)
                .HasComment("المحافظة")
                .HasColumnName("STATE_ID");
            entity.Property(e => e.Tel)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasComment("هاتف")
                .HasColumnName("TEL");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
            entity.Property(e => e.WorkNatureId)
                .HasPrecision(9)
                .HasComment("طبيعة العمل")
                .HasColumnName("WORK_NATURE_ID");
            entity.Property(e => e.WorkPlace)
                .IsRequired()
                .HasMaxLength(200)
                .HasComment("مكان العمل")
                .HasColumnName("WORK_PLACE");
            entity.Property(e => e.WorkingYears)
                .HasPrecision(3)
                .HasComment("سنوات الخدمة")
                .HasColumnName("WORKING_YEARS");

            entity.HasOne(d => d.Profile).WithMany(p => p.ProfileWorksTbs)
                .HasForeignKey(d => d.ProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PROFILE_WORKS_FK");
        });

        modelBuilder.Entity<ProfilesPartnersTb>(entity =>
        {
            entity.HasKey(e => e.PartnerId).HasName("PROFILES_PARTNERS_TB_PK");

            entity.ToTable("PROFILES_PARTNERS_TB");

            entity.HasIndex(e => new { e.IdTypeId, e.IdNum }, "PROFILES_PARTNERS_TB_I4");

            entity.Property(e => e.PartnerId)
                .HasPrecision(9)
                .ValueGeneratedNever()
                .HasComment("رقم الشريك")
                .HasColumnName("PARTNER_ID");
            entity.Property(e => e.Address)
                .HasMaxLength(300)
                .HasComment("العنوان")
                .HasColumnName("ADDRESS");
            entity.Property(e => e.BirthDate)
                .HasComment("تاريخ الميلاد")
                .HasColumnType("DATE")
                .HasColumnName("BIRTH_DATE");
            entity.Property(e => e.BirthPlace)
                .HasMaxLength(200)
                .HasComment("مكان الميلاد")
                .HasColumnName("BIRTH_PLACE");
            entity.Property(e => e.CelularNumber)
                .HasMaxLength(30)
                .HasComment("رقم الهاتف المتنقل")
                .HasColumnName("CELULAR_NUMBER");
            entity.Property(e => e.CityId)
                .HasPrecision(9)
                .HasComment("المدينة")
                .HasColumnName("CITY_ID");
            entity.Property(e => e.CompanyNotes)
                .IsUnicode(false)
                .HasComment("ملاحظات حول الشركة التابعة ")
                .HasColumnName("COMPANY_NOTES");
            entity.Property(e => e.ContributionPercent)
                .HasComment("نسبة المساهمة")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("CONTRIBUTION_PERCENT");
            entity.Property(e => e.CountryId)
                .HasPrecision(9)
                .HasComment("الدولة")
                .HasColumnName("COUNTRY_ID");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CurrentExperienceNotes)
                .IsUnicode(false)
                .HasComment("تفاصيل الخبرة للعمل الحالي")
                .HasColumnName("CURRENT_EXPERIENCE_NOTES");
            entity.Property(e => e.CustTypeId)
                .HasComment("نوع الشريك")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CUST_TYPE_ID");
            entity.Property(e => e.DependentsCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد المعالين ")
                .HasColumnName("DEPENDENTS_CNT");
            entity.Property(e => e.EducationLevelId)
                .HasPrecision(9)
                .HasComment("المؤهل العلمي")
                .HasColumnName("EDUCATION_LEVEL_ID");
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .HasComment("البريد الالكتروني")
                .HasColumnName("EMAIL");
            entity.Property(e => e.ExperienceYearsCnt)
                .HasPrecision(9)
                .HasComment("سنوات الخبرة للعمل الحالي")
                .HasColumnName("EXPERIENCE_YEARS_CNT");
            entity.Property(e => e.FamilyNameNa)
                .HasMaxLength(50)
                .HasComment("اسم العائلة باللغة المحلية")
                .HasColumnName("FAMILY_NAME_NA");
            entity.Property(e => e.FatherNameNa)
                .HasMaxLength(50)
                .HasComment("اسم الأب باللغة المحلية")
                .HasColumnName("FATHER_NAME_NA");
            entity.Property(e => e.FirstNameNa)
                .HasMaxLength(50)
                .HasComment("الاسم الشخصي باللغة المحلية")
                .HasColumnName("FIRST_NAME_NA");
            entity.Property(e => e.GenderId)
                .HasComment("الجنس")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("GENDER_ID");
            entity.Property(e => e.GrandFatherNameNa)
                .HasMaxLength(50)
                .HasComment("اسم الجد باللغة المحلية")
                .HasColumnName("GRAND_FATHER_NAME_NA");
            entity.Property(e => e.IdNum)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("رقم وثيقة التعريف")
                .HasColumnName("ID_NUM");
            entity.Property(e => e.IdTypeId)
                .HasPrecision(9)
                .HasDefaultValueSql("1 ")
                .HasComment("نوع وثيقة التعريف\n1 = هوية\n2= VAT NUMBER مشتغل مرخص\n3= جواز سفر فلسطيني\n4 = جواز سفر أردني\n.....")
                .HasColumnName("ID_TYPE_ID");
            entity.Property(e => e.IsBankBorrower)
                .HasComment("مقترض قائم نعم =  2\nلا = 1")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_BANK_BORROWER");
            entity.Property(e => e.IsHidden)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("الحالة\nفعال=0\nغير فعال=1")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_HIDDEN");
            entity.Property(e => e.MaritalStatusId)
                .HasPrecision(2)
                .HasComment("الحالة الإجتماعية")
                .HasColumnName("MARITAL_STATUS_ID");
            entity.Property(e => e.Notes)
                .IsUnicode(false)
                .HasComment("ملاحظات")
                .HasColumnName("NOTES");
            entity.Property(e => e.OtherExperienceNotes)
                .IsUnicode(false)
                .HasComment("الخبرة في مجالات اخرى")
                .HasColumnName("OTHER_EXPERIENCE_NOTES");
            entity.Property(e => e.PartnerFullName)
                .HasMaxLength(200)
                .HasComment("اسم الشريك الرباعي")
                .HasColumnName("PARTNER_FULL_NAME");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(30)
                .HasComment("رقم الهاتف الارضي")
                .HasColumnName("PHONE_NUMBER");
            entity.Property(e => e.ProfileId)
                .HasPrecision(9)
                .HasComment("رقم الملف")
                .HasColumnName("PROFILE_ID");
            entity.Property(e => e.ResidentFlag)
                .HasDefaultValueSql("1")
                .HasComment("العميل:\n1- مقيم\n2- غير مقيم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("RESIDENT_FLAG");
            entity.Property(e => e.SharesCnt)
                .HasPrecision(9)
                .HasComment("عدد الأسهم")
                .HasColumnName("SHARES_CNT");
            entity.Property(e => e.StateId)
                .HasPrecision(9)
                .HasComment("المحافظة")
                .HasColumnName("STATE_ID");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Profile).WithMany(p => p.ProfilesPartnersTbs)
                .HasForeignKey(d => d.ProfileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RHODES_BANKING_FK");
        });

        modelBuilder.Entity<ProfilesTb>(entity =>
        {
            entity.HasKey(e => e.ProfileId).HasName("PROFILES_PK");

            entity.ToTable("PROFILES_TB", tb => tb.HasComment("الملفات\nالشركات، الأفراد ، العملاء،  الزوجات، الكفلاء..."));

            entity.HasIndex(e => e.ProfileNameNa, "PROFILES_I1");

            entity.HasIndex(e => e.CustId, "PROFILES_I2").IsUnique();

            entity.HasIndex(e => e.ProfileNameFNa, "PROFILES_I3");

            entity.HasIndex(e => new { e.IdNum, e.IdTypeId }, "PROFILES_I4").IsUnique();

            entity.Property(e => e.ProfileId)
                .HasPrecision(9)
                .ValueGeneratedNever()
                .HasComment("رقم الملف")
                .HasColumnName("PROFILE_ID");
            entity.Property(e => e.AccommodationTypeId)
                .HasPrecision(9)
                .HasComment("نوع الاقامة في فلسطين محلية أو أجنبية")
                .HasColumnName("ACCOMMODATION_TYPE_ID");
            entity.Property(e => e.AccountManagerUserId)
                .HasPrecision(9)
                .HasComment("مدير الحساب")
                .HasColumnName("ACCOUNT_MANAGER_USER_ID");
            entity.Property(e => e.ActivityId)
                .HasPrecision(9)
                .HasComment("نوع النشاط")
                .HasColumnName("ACTIVITY_ID");
            entity.Property(e => e.ActivityName)
                .HasMaxLength(1000)
                .HasComment("النشاط")
                .HasColumnName("ACTIVITY_NAME");
            entity.Property(e => e.ActualActivityDate)
                .HasComment("تاريخ ممارسة النشاط الفعلي")
                .HasColumnType("DATE")
                .HasColumnName("ACTUAL_ACTIVITY_DATE");
            entity.Property(e => e.AnnualSalesRate)
                .HasComment("معدل المبيعات سنويا")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("ANNUAL_SALES_RATE");
            entity.Property(e => e.AnnualSalesRateCurrId)
                .HasPrecision(3)
                .HasComment("عملة معدل المبيعات")
                .HasColumnName("ANNUAL_SALES_RATE_CURR_ID");
            entity.Property(e => e.BirthDate)
                .HasComment("تاريخ الميلاد")
                .HasColumnType("DATE")
                .HasColumnName("BIRTH_DATE");
            entity.Property(e => e.BirthPlace)
                .HasMaxLength(200)
                .HasComment("مكان الميلاد")
                .HasColumnName("BIRTH_PLACE");
            entity.Property(e => e.BlackListCount)
                .HasPrecision(9)
                .HasDefaultValueSql("0")
                .HasComment("الحالة : و تمثل عدد مرات الإضافة على القائمة مطروحاً منها عدد مرات الإلغاء\nيتم تعديل بيانات السجل وكذلك العميل لنفس الحقل بناءً على رقم العميل\n0= تم إضافته و إلغاؤه أي خرج من القائمة السوداء\n>0 مازال على القئمة السوداء")
                .HasColumnName("BLACK_LIST_COUNT");
            entity.Property(e => e.BranchId)
                .HasPrecision(9)
                .HasComment("رقم الفرع")
                .HasColumnName("BRANCH_ID");
            entity.Property(e => e.BrothersNoWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد غير العاملين من الأخوة والأخوات")
                .HasColumnName("BROTHERS_NO_WORK_CNT");
            entity.Property(e => e.BrothersWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد العاملين من الأخوة والأخوات")
                .HasColumnName("BROTHERS_WORK_CNT");
            entity.Property(e => e.Capital)
                .HasComment("رأس المال\n")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("CAPITAL");
            entity.Property(e => e.CapitalAuthorizedPaid)
                .HasComment("رأس المال المصرح به و المدفوع")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("CAPITAL_AUTHORIZED_PAID");
            entity.Property(e => e.ChairmanName)
                .HasMaxLength(200)
                .HasComment(" اسم رئيس الهيئة")
                .HasColumnName("CHAIRMAN_NAME");
            entity.Property(e => e.ChildrenCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد الاولاد الكلي")
                .HasColumnName("CHILDREN_CNT");
            entity.Property(e => e.ChildrenNoWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد غير العاملين من الأبناء")
                .HasColumnName("CHILDREN_NO_WORK_CNT");
            entity.Property(e => e.ChildrenUnderEightteenCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد الأولاد تحت سن 18 سنة ")
                .HasColumnName("CHILDREN_UNDER_EIGHTTEEN_CNT");
            entity.Property(e => e.ChildrenWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد العاملين من الأبناء")
                .HasColumnName("CHILDREN_WORK_CNT");
            entity.Property(e => e.ChronicDetails)
                .HasComment("وصف الإعاقة أو الأمراض المزمنة")
                .HasColumnName("CHRONIC_DETAILS");
            entity.Property(e => e.ChronicFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل يوجد أحد من أفراد الأسرة لديه مرض مزمن أو إعاقة\n0 = no\n1 = yes")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CHRONIC_FLAG");
            entity.Property(e => e.ClassId)
                .HasPrecision(9)
                .HasComment("تصنيف العميل")
                .HasColumnName("CLASS_ID");
            entity.Property(e => e.CommercialName)
                .HasMaxLength(200)
                .HasComment("الاسم التجاري")
                .HasColumnName("COMMERCIAL_NAME");
            entity.Property(e => e.CreatedBy)
                .HasPrecision(9)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasDefaultValueSql("SYSDATE")
                .HasColumnType("DATE")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.CurrAddress)
                .HasMaxLength(300)
                .HasComment("العنوان الحالي - العنوان\nللشركات = عنوان المركز الرئيسي")
                .HasColumnName("CURR_ADDRESS");
            entity.Property(e => e.CurrCityId)
                .HasPrecision(9)
                .HasComment("العنوان الحالي - المدينة\nللشركات = عنوان المركز الرئيسي")
                .HasColumnName("CURR_CITY_ID");
            entity.Property(e => e.CurrCountryId)
                .HasPrecision(9)
                .HasComment("العنوان الحالي - الدولة\nللشركات = عنوان المركز الرئيسي")
                .HasColumnName("CURR_COUNTRY_ID");
            entity.Property(e => e.CurrHomeOwnershipId)
                .HasDefaultValueSql("1")
                .HasComment("العنوان الحالي - ملكية السكن\nللأفراد فقط")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CURR_HOME_OWNERSHIP_ID");
            entity.Property(e => e.CurrId)
                .HasPrecision(3)
                .HasComment("العملة")
                .HasColumnName("CURR_ID");
            entity.Property(e => e.CurrStateId)
                .HasPrecision(9)
                .HasComment("العنوان الحالي -  المحافظة\nللشركات = عنوان المركز الرئيسي")
                .HasColumnName("CURR_STATE_ID");
            entity.Property(e => e.CustApprovedBy)
                .HasPrecision(9)
                .HasComment("الموافقة بواسطة")
                .HasColumnName("CUST_APPROVED_BY");
            entity.Property(e => e.CustApprovedOn)
                .HasComment("تاريخ الموافقة")
                .HasColumnType("DATE")
                .HasColumnName("CUST_APPROVED_ON");
            entity.Property(e => e.CustId)
                .HasPrecision(19)
                .HasComment("رقم العميل\nSERIAL")
                .HasColumnName("CUST_ID");
            entity.Property(e => e.CustStatusId)
                .IsRequired()
                .HasDefaultValueSql("1 ")
                .HasComment("حالة العميل\n1 = فعال\n0 = غير فعال")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CUST_STATUS_ID");
            entity.Property(e => e.CustTypeId)
                .HasComment("نوع العميل\n1=FIRM\n2=INDIVIDUAL\n")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("CUST_TYPE_ID");
            entity.Property(e => e.DataExpiryDate)
                .HasComment("تاريخ انتهاء صلاحية البيانات وتحدد من الاعدادت حسب اخر تعديل على بيانات الحساب")
                .HasColumnType("DATE")
                .HasColumnName("DATA_EXPIRY_DATE");
            entity.Property(e => e.DeathDate)
                .HasComment("تاريخ الوفاة")
                .HasColumnType("DATE")
                .HasColumnName("DEATH_DATE");
            entity.Property(e => e.DebtLimitDuration)
                .HasPrecision(9)
                .HasComment("مدة حد الدين بالأشهر")
                .HasColumnName("DEBT_LIMIT_DURATION");
            entity.Property(e => e.DebtLimitPeriodId)
                .HasPrecision(9)
                .HasDefaultValueSql("2")
                .HasComment("نوع مدة حد الدين\n2=شهر")
                .HasColumnName("DEBT_LIMIT_PERIOD_ID");
            entity.Property(e => e.DebtLimitValue)
                .HasDefaultValueSql("0")
                .HasComment("حد الدين")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("DEBT_LIMIT_VALUE");
            entity.Property(e => e.DependentsCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد المعالين ")
                .HasColumnName("DEPENDENTS_CNT");
            entity.Property(e => e.DependentsFemalesCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد الإناث (المعالين)")
                .HasColumnName("DEPENDENTS_FEMALES_CNT");
            entity.Property(e => e.DependentsMalesCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد الذكور (المعالين)")
                .HasColumnName("DEPENDENTS_MALES_CNT");
            entity.Property(e => e.EconomicActivityId)
                .HasPrecision(9)
                .HasComment("النشاط الاقتصادي")
                .HasColumnName("ECONOMIC_ACTIVITY_ID");
            entity.Property(e => e.EconomicSectorId)
                .HasPrecision(9)
                .HasComment("القطاع الإقتصادي\n\nرقم 148 في جدول الثوابت")
                .HasColumnName("ECONOMIC_SECTOR_ID");
            entity.Property(e => e.EducationLevelId)
                .HasPrecision(9)
                .HasComment("المستوى التعليمي")
                .HasColumnName("EDUCATION_LEVEL_ID");
            entity.Property(e => e.EmployeesFemaleCnt)
                .HasPrecision(9)
                .HasComment("عدد العاملين الاناث")
                .HasColumnName("EMPLOYEES_FEMALE_CNT");
            entity.Property(e => e.EmployeesMaleCnt)
                .HasPrecision(9)
                .HasComment("عدد العاملين الذكور")
                .HasColumnName("EMPLOYEES_MALE_CNT");
            entity.Property(e => e.EmployerId)
                .HasPrecision(9)
                .HasComment("الجهة المشغلة - صاحب العمل")
                .HasColumnName("EMPLOYER_ID");
            entity.Property(e => e.EntrySourceId)
                .IsRequired()
                .HasDefaultValueSql("1 ")
                .HasComment("مصدر إدخال البيانات\n1 = الشركة\n2 = الشخص نفسه")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("ENTRY_SOURCE_ID");
            entity.Property(e => e.ExpiryDate)
                .HasComment("تاريخ الإنتهاء")
                .HasColumnType("DATE")
                .HasColumnName("EXPIRY_DATE");
            entity.Property(e => e.ExtFacilitiesCurrId)
                .HasPrecision(3)
                .HasComment("عملة التسهيلات الخارجية")
                .HasColumnName("EXT_FACILITIES_CURR_ID");
            entity.Property(e => e.ExtFacilitiesMonthlyInst)
                .HasComment("القسط الشهري للتسهيلات الخارجية")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("EXT_FACILITIES_MONTHLY_INST");
            entity.Property(e => e.ExtGuaranteesCurrId)
                .HasPrecision(3)
                .HasComment("عملة الكفالات الخارجية")
                .HasColumnName("EXT_GUARANTEES_CURR_ID");
            entity.Property(e => e.ExtGuaranteesMonthlyInst)
                .HasComment("القسط الشهري للكفالات الخارجية")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("EXT_GUARANTEES_MONTHLY_INST");
            entity.Property(e => e.FamilyMembersCnt)
                .HasPrecision(4)
                .HasComment("عدد افراد الأسرة")
                .HasColumnName("FAMILY_MEMBERS_CNT");
            entity.Property(e => e.FamilyNameFo)
                .HasMaxLength(50)
                .HasComment("اسم العائلة باللغة الأجنبية")
                .HasColumnName("FAMILY_NAME_FO");
            entity.Property(e => e.FamilyNameNa)
                .HasMaxLength(50)
                .HasComment("اسم العائلة باللغة المحلية")
                .HasColumnName("FAMILY_NAME_NA");
            entity.Property(e => e.FatherNameFo)
                .HasMaxLength(50)
                .HasComment("اسم الأب باللغة الأجنبية")
                .HasColumnName("FATHER_NAME_FO");
            entity.Property(e => e.FatherNameNa)
                .HasMaxLength(50)
                .HasComment("اسم الأب باللغة المحلية")
                .HasColumnName("FATHER_NAME_NA");
            entity.Property(e => e.FinancialClassId)
                .HasPrecision(9)
                .HasComment("رقم التصنيف  المالي للعميل  ")
                .HasColumnName("FINANCIAL_CLASS_ID");
            entity.Property(e => e.FirmLegalTypeId)
                .HasPrecision(9)
                .HasComment("الشكل القانوني")
                .HasColumnName("FIRM_LEGAL_TYPE_ID");
            entity.Property(e => e.FirmTypeId)
                .HasPrecision(9)
                .HasComment("نوع المؤسسة")
                .HasColumnName("FIRM_TYPE_ID");
            entity.Property(e => e.FirstNameFo)
                .HasMaxLength(50)
                .HasComment("الاسم الشخصي باللغة الأجنبية")
                .HasColumnName("FIRST_NAME_FO");
            entity.Property(e => e.FirstNameNa)
                .HasMaxLength(50)
                .HasComment("الاسم الشخصي باللغة المحلية")
                .HasColumnName("FIRST_NAME_NA");
            entity.Property(e => e.GenderId)
                .HasComment("الجنس")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("GENDER_ID");
            entity.Property(e => e.GrandFatherNameFo)
                .HasMaxLength(50)
                .HasComment("اسم الجد باللغة الأجنبية")
                .HasColumnName("GRAND_FATHER_NAME_FO");
            entity.Property(e => e.GrandFatherNameNa)
                .HasMaxLength(50)
                .HasComment("اسم الجد باللغة المحلية")
                .HasColumnName("GRAND_FATHER_NAME_NA");
            entity.Property(e => e.GroupId)
                .HasPrecision(9)
                .HasComment("رقم المجموعة")
                .HasColumnName("GROUP_ID");
            entity.Property(e => e.GroupName)
                .HasMaxLength(200)
                .HasComment("اسم المجموعة")
                .HasColumnName("GROUP_NAME");
            entity.Property(e => e.HasBoardMembersFlag)
                .HasDefaultValueSql("1")
                .HasComment("هل لديه اعضاء مجلس ادارة\n0 لا\n1 نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_BOARD_MEMBERS_FLAG");
            entity.Property(e => e.HasCompetitorsFlag)
                .HasDefaultValueSql("1")
                .HasComment("هل لديه منافسين\n0 لا\n1 نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_COMPETITORS_FLAG");
            entity.Property(e => e.HasExtFacilitiesFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل عليه لتسهيلات خارجية\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_EXT_FACILITIES_FLAG");
            entity.Property(e => e.HasExtGuaranteesFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل عليه كفالات خارجية\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_EXT_GUARANTEES_FLAG");
            entity.Property(e => e.HasPoliticalOwnersFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل يعتبر أحد المالكين، المفوضين بالتوقيع، المدراء التنفيذيين من المتنفذين السياسيين/ القضائيين/ العسكريين \n \n1- نعم \n0- لا")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_POLITICAL_OWNERS_FLAG");
            entity.Property(e => e.HasPoliticalRelativesFlag)
                .HasDefaultValueSql("0")
                .HasComment("له أقارب سياسيون\n 0 لا\n 1 نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("HAS_POLITICAL_RELATIVES_FLAG");
            entity.Property(e => e.Hight)
                .HasPrecision(3)
                .HasComment("الطول")
                .HasColumnName("HIGHT");
            entity.Property(e => e.IdNum)
                .HasMaxLength(100)
                .HasComment("رقم وثيقة التعريف")
                .HasColumnName("ID_NUM");
            entity.Property(e => e.IdTypeId)
                .HasPrecision(9)
                .HasDefaultValueSql("1")
                .HasComment("نوع وثيقة التعريف\n1 = هوية\n2= VAT NUMBER مشتغل مرخص\n3= جواز سفر فلسطيني\n4 = جواز سفر أردني\n.....")
                .HasColumnName("ID_TYPE_ID");
            entity.Property(e => e.IncomeAmount)
                .HasDefaultValueSql("0")
                .HasComment("القيمة")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("INCOME_AMOUNT");
            entity.Property(e => e.IncomeCurrId)
                .HasPrecision(3)
                .HasComment("العملة")
                .HasColumnName("INCOME_CURR_ID");
            entity.Property(e => e.IsCompleated)
                .HasDefaultValueSql("0")
                .HasComment("هل بيانات العميل مكتملة \n0=لا \n1=نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_COMPLEATED");
            entity.Property(e => e.IsCustomer)
                .HasDefaultValueSql("0")
                .HasComment("هل البروفايل لعميل\n0=لا\n1=نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_CUSTOMER");
            entity.Property(e => e.IsInRisk)
                .HasDefaultValueSql("0")
                .HasComment("هل معرض للخطر\n1 نعم\n0 لا")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_IN_RISK");
            entity.Property(e => e.IsPortalCompleated)
                .HasDefaultValueSql("0")
                .HasComment("هل بيانات العميل بالنسبة للبورتال مكتملة\n0 لا\n1 نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("IS_PORTAL_COMPLEATED");
            entity.Property(e => e.IssueDate)
                .HasComment("تاريخ الإصدار")
                .HasColumnType("DATE")
                .HasColumnName("ISSUE_DATE");
            entity.Property(e => e.IssuePlace)
                .HasMaxLength(500)
                .HasComment("مكان الإصدار")
                .HasColumnName("ISSUE_PLACE");
            entity.Property(e => e.IssuePlaceId)
                .HasPrecision(9)
                .HasComment("مكان إصدار الوثيقة من المحافظات الفلسطينية")
                .HasColumnName("ISSUE_PLACE_ID");
            entity.Property(e => e.IssuerCertificateRegisterId)
                .HasPrecision(9)
                .HasComment("جهة الإصدار لشهادة التسجيل")
                .HasColumnName("ISSUER_CERTIFICATE_REGISTER_ID");
            entity.Property(e => e.IstablishmentDate)
                .HasComment("تاريخ التأسيس")
                .HasColumnType("DATE")
                .HasColumnName("ISTABLISHMENT_DATE");
            entity.Property(e => e.LatestRegCirtificate)
                .HasComment("تاريخ اخر اصدار لشهادة التسجيل")
                .HasColumnType("DATE")
                .HasColumnName("LATEST_REG_CIRTIFICATE");
            entity.Property(e => e.MailAddress)
                .HasMaxLength(300)
                .HasComment("عنوان المراسلة - العنوان")
                .HasColumnName("MAIL_ADDRESS");
            entity.Property(e => e.MailAddressFlag)
                .IsRequired()
                .HasDefaultValueSql("1 ")
                .HasComment("اعتماد بيانات المراسلة نفس بيانات العنوان الحالي\n1 = YES\n0 = NO")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("MAIL_ADDRESS_FLAG");
            entity.Property(e => e.MailCityId)
                .HasPrecision(9)
                .HasComment("عنوان المراسلة -  المدينة")
                .HasColumnName("MAIL_CITY_ID");
            entity.Property(e => e.MailCountryId)
                .HasPrecision(9)
                .HasComment("عنوان المراسلة - الدولة")
                .HasColumnName("MAIL_COUNTRY_ID");
            entity.Property(e => e.MailFax)
                .HasMaxLength(30)
                .HasComment("رقم الفاكس\n")
                .HasColumnName("MAIL_FAX");
            entity.Property(e => e.MailLangId)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasComment("لغة المراسلة\nAR,EN,FR,....")
                .HasColumnName("MAIL_LANG_ID");
            entity.Property(e => e.MailPobox)
                .HasMaxLength(15)
                .HasComment("رقم بريد المراسلة")
                .HasColumnName("MAIL_POBOX");
            entity.Property(e => e.MailStateId)
                .HasPrecision(9)
                .HasComment("عنوان المراسلة - المحافظة")
                .HasColumnName("MAIL_STATE_ID");
            entity.Property(e => e.MailTelex)
                .HasMaxLength(30)
                .HasComment("رقم التلكس\n")
                .HasColumnName("MAIL_TELEX");
            entity.Property(e => e.MailZip)
                .HasMaxLength(15)
                .HasComment("الرمز البريدي")
                .HasColumnName("MAIL_ZIP");
            entity.Property(e => e.MaritalStatusId)
                .HasPrecision(2)
                .HasComment("الحالة الإجتماعية")
                .HasColumnName("MARITAL_STATUS_ID");
            entity.Property(e => e.MaxCollectionChecksValue)
                .HasDefaultValueSql("0")
                .HasComment("الحد الأقصى للشيكات رسم التحصيل (العملة الافتراضية للنظام)")
                .HasColumnType("NUMBER(20,3)")
                .HasColumnName("MAX_COLLECTION_CHECKS_VALUE");
            entity.Property(e => e.MotherName)
                .HasMaxLength(200)
                .HasComment("اسم الام")
                .HasColumnName("MOTHER_NAME");
            entity.Property(e => e.NickName)
                .HasMaxLength(100)
                .HasComment("الكنية - اسم الشهرة")
                .HasColumnName("NICK_NAME");
            entity.Property(e => e.Notes)
                .HasComment("ملاحظات")
                .HasColumnName("NOTES");
            entity.Property(e => e.NumberOfBranches)
                .HasPrecision(9)
                .HasComment("عدد الفروع")
                .HasColumnName("NUMBER_OF_BRANCHES");
            entity.Property(e => e.NumberOfEmployees)
                .HasPrecision(9)
                .HasComment("عدد الموظفين")
                .HasColumnName("NUMBER_OF_EMPLOYEES");
            entity.Property(e => e.NumberOfVehicles)
                .HasPrecision(9)
                .HasComment("عدد المركبات")
                .HasColumnName("NUMBER_OF_VEHICLES");
            entity.Property(e => e.ParentsNoWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد غير العاملين من الأهل(الأب والام)")
                .HasColumnName("PARENTS_NO_WORK_CNT");
            entity.Property(e => e.ParentsWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد العاملين من الأهل(الأب والام)")
                .HasColumnName("PARENTS_WORK_CNT");
            entity.Property(e => e.PermanentAddress)
                .HasMaxLength(300)
                .HasComment("العنوان الدائم - العنوان\nللشركات = عنوان مزاولة العمل")
                .HasColumnName("PERMANENT_ADDRESS");
            entity.Property(e => e.PermanentAddressFlag)
                .IsRequired()
                .HasDefaultValueSql("1 ")
                .HasComment("اعتماد بيانات العنوان الدائم نفس بيانات العنوان الحالي\n1 = YES\n0 = NO")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("PERMANENT_ADDRESS_FLAG");
            entity.Property(e => e.PermanentCityId)
                .HasPrecision(9)
                .HasComment("العنوان الدائم -  المدينة\nللشركات = عنوان مزاولة العمل")
                .HasColumnName("PERMANENT_CITY_ID");
            entity.Property(e => e.PermanentCountryId)
                .HasPrecision(9)
                .HasComment("العنوان الدائم -  الدولة\nللشركات = عنوان مزاولة العمل")
                .HasColumnName("PERMANENT_COUNTRY_ID");
            entity.Property(e => e.PermanentHomeOwnershipId)
                .HasDefaultValueSql("1")
                .HasComment("العنوان الدائم - ملكية السكن\nللافراد فقط")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("PERMANENT_HOME_OWNERSHIP_ID");
            entity.Property(e => e.PermanentStateId)
                .HasPrecision(9)
                .HasComment("العنوان الدائم - المحافظة\nللشركات = عنوان مزاولة العمل")
                .HasColumnName("PERMANENT_STATE_ID");
            entity.Property(e => e.PositionId)
                .HasPrecision(9)
                .HasComment("المنصب")
                .HasColumnName("POSITION_ID");
            entity.Property(e => e.PositionTitle)
                .HasMaxLength(200)
                .HasComment("مسمى المنصب")
                .HasColumnName("POSITION_TITLE");
            entity.Property(e => e.ProfileNameFFo)
                .HasMaxLength(200)
                .HasComment("الاسم مفلتر")
                .HasColumnName("PROFILE_NAME_F_FO");
            entity.Property(e => e.ProfileNameFNa)
                .HasMaxLength(200)
                .HasComment("الاسم مفلتر")
                .HasColumnName("PROFILE_NAME_F_NA");
            entity.Property(e => e.ProfileNameFo)
                .HasMaxLength(200)
                .HasComment("اسم صاحب الملف")
                .HasColumnName("PROFILE_NAME_FO");
            entity.Property(e => e.ProfileNameNa)
                .IsRequired()
                .HasMaxLength(200)
                .HasComment("اسم صاحب الملف")
                .HasColumnName("PROFILE_NAME_NA");
            entity.Property(e => e.ResidentFlag)
                .IsRequired()
                .HasDefaultValueSql("1 ")
                .HasComment("مقيم\n0 = غير مقيم\n1 = مقيم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("RESIDENT_FLAG");
            entity.Property(e => e.ReviewFlag)
                .IsRequired()
                .HasDefaultValueSql("0 ")
                .HasComment("هل تمت مراجعة البيانات من قبل الشركة\n0 = لا\n1 = نعم")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("REVIEW_FLAG");
            entity.Property(e => e.RiskTypeId)
                .HasPrecision(9)
                .HasComment("نوع الخطر (عالي، متوسط، منخفض)")
                .HasColumnName("RISK_TYPE_ID");
            entity.Property(e => e.SectorId)
                .HasPrecision(9)
                .HasComment("القطاع\n1 = خاص \n2 = حكومي")
                .HasColumnName("SECTOR_ID");
            entity.Property(e => e.SendAccountStatementId)
                .HasPrecision(3)
                .HasDefaultValueSql("0")
                .HasComment("إرسال كشف الحساب\n0 = بدون إرسال\n1= شهري MONTHLY\n2 = ربع سنوي QUARTERLY YEARLY\n3 = نص سنوي HALF YEARLY\n4 = سنوي YEARLY ")
                .HasColumnName("SEND_ACCOUNT_STATEMENT_ID");
            entity.Property(e => e.SendAccountStatementViaId)
                .HasPrecision(4)
                .HasComment("يرسل كشف حساب عبر \n \nرقم 114 في الثوابت")
                .HasColumnName("SEND_ACCOUNT_STATEMENT_VIA_ID");
            entity.Property(e => e.ShortName)
                .HasMaxLength(200)
                .HasComment("الاسم المختصر للعميل باللغة المحلية")
                .HasColumnName("SHORT_NAME");
            entity.Property(e => e.SpecialNeedsFlag)
                .HasDefaultValueSql("0")
                .HasComment("هل العميل من ذوي الاحتياجات الخاصة او لديه مرض مزمن؟\n1 = yes\n0 = no")
                .HasColumnType("NUMBER(1)")
                .HasColumnName("SPECIAL_NEEDS_FLAG");
            entity.Property(e => e.SpouseNoWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد غير العاملين من الزوج/الزوجة")
                .HasColumnName("SPOUSE_NO_WORK_CNT");
            entity.Property(e => e.SpouseWorkCnt)
                .HasPrecision(4)
                .HasDefaultValueSql("0")
                .HasComment("عدد العاملين من الزوج/الزوجة")
                .HasColumnName("SPOUSE_WORK_CNT");
            entity.Property(e => e.StatusUpdatedBy)
                .HasPrecision(9)
                .HasColumnName("STATUS_UPDATED_BY");
            entity.Property(e => e.StatusUpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("STATUS_UPDATED_ON");
            entity.Property(e => e.TitleId)
                .HasPrecision(9)
                .HasComment("اللقب")
                .HasColumnName("TITLE_ID");
            entity.Property(e => e.UpdatedBy)
                .HasPrecision(9)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn)
                .HasColumnType("DATE")
                .HasColumnName("UPDATED_ON");
            entity.Property(e => e.VatNum)
                .HasMaxLength(100)
                .HasComment("الرقم الضريبي")
                .HasColumnName("VAT_NUM");
            entity.Property(e => e.Weight)
                .HasPrecision(3)
                .HasComment("الوزن")
                .HasColumnName("WEIGHT");

            entity.HasOne(d => d.Branch).WithMany(p => p.ProfilesTbs)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("BRANCHES_FK");
        });
        modelBuilder.HasSequence("ACCOUNT_ATTACHMENTS_TB_SEQ");
        modelBuilder.HasSequence("ACTIVITY_SELLING_METHODS_SEQ");
        modelBuilder.HasSequence("ARREARS_PROV_SET_TB_SEQ");
        modelBuilder.HasSequence("ATTACHMENTS_SEQ");
        modelBuilder.HasSequence("AUDIT_LOGS_TB_SEQ");
        modelBuilder.HasSequence("BACKUP_REQUEST_COMMAND_STEP_ROLES_SEQ");
        modelBuilder.HasSequence("BIND_DEPOSIT_SETTINGS_SEQ");
        modelBuilder.HasSequence("C_COMMISSION_TYPE_CEIL_SEQ");
        modelBuilder.HasSequence("C_DEPOSIT_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("C_DEPOSIT_TYPE_PERIODS_SEQ");
        modelBuilder.HasSequence("C_DEPOSIT_TYPES_SEQ");
        modelBuilder.HasSequence("C_FINANCING_PURPOSES_TB_SEQ");
        modelBuilder.HasSequence("C_FUND_PROCEDURES_SEQ");
        modelBuilder.HasSequence("C_GUARANTEE_TYPES_TB_SEQ");
        modelBuilder.HasSequence("C_MINERALS_TB_SEQ");
        modelBuilder.HasSequence("C_NOTIFICATION_TYPES_SEQ");
        modelBuilder.HasSequence("C_PRODUCT_SUB_TITLES_TB_SEQ");
        modelBuilder.HasSequence("C_PRODUCT_TYPES_TB_SEQ");
        modelBuilder.HasSequence("C_PROGRAMS_TYPES_TB_SEQ");
        modelBuilder.HasSequence("C_REAL_ESTATE_TYPES_SEQ");
        modelBuilder.HasSequence("C_RESERVATION_REASON_TB_SEQ");
        modelBuilder.HasSequence("C_ROLES_SEQ");
        modelBuilder.HasSequence("C_SAVING_ACC_INTERESTS_SEQ");
        modelBuilder.HasSequence("C_STOCKS_TB_SEQ");
        modelBuilder.HasSequence("C_VEHICLE_MODELS_TB_SEQ");
        modelBuilder.HasSequence("C_VEHICLES_TYPES_TB_SEQ");
        modelBuilder.HasSequence("CHANGED_ROLE_USERS_TB_SEQ");
        modelBuilder.HasSequence("CHECK_BOOK_TRANS_TB_SEQ");
        modelBuilder.HasSequence("CHECK_BOOKS_TB_SEQ");
        modelBuilder.HasSequence("CHECK_DESTRUCTION_TB_SEQ");
        modelBuilder.HasSequence("CHECK_REASONS_SEQ");
        modelBuilder.HasSequence("CLOSING_LOGS_SEQ");
        modelBuilder.HasSequence("COMMISSION_INCOME_TB_SEQ");
        modelBuilder.HasSequence("CRM_TICKET_COMMENTS_SEQ");
        modelBuilder.HasSequence("CRM_TICKETS_SEQ");
        modelBuilder.HasSequence("CURRENT_ACCOUNT_PENALTIES_SEQ");
        modelBuilder.HasSequence("CUST_COMM_TYPE_CEIL_SEQ");
        modelBuilder.HasSequence("CUST_COMM_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("CUST_DEPOSIT_TYPES_SEQ");
        modelBuilder.HasSequence("CUST_SCREEN_COMMAND_REQUEST_TB_SEQ");
        modelBuilder.HasSequence("CUSTOMERS_BENEFICIARIES_SEQ");
        modelBuilder.HasSequence("CUSTOMERS_SEQ");
        modelBuilder.HasSequence("CUSTOMIZED_FIELD_ITMES_SEQ");
        modelBuilder.HasSequence("CUSTOMIZED_FIELDS_SEQ");
        modelBuilder.HasSequence("DELAY_POSTING_REF_NUM_SEQ");
        modelBuilder.HasSequence("DELEGATION_GROUP_ACC_SEQ");
        modelBuilder.HasSequence("DELEGATION_GROUP_DELEGS_SEQ");
        modelBuilder.HasSequence("DELEGATION_GROUP_TRANS_SEQ");
        modelBuilder.HasSequence("DELEGATION_GROUPS_SEQ");
        modelBuilder.HasSequence("DELEGATION_PERSON_TRANS_SEQ");
        modelBuilder.HasSequence("DEPOSIT_MONTHLY_POSTS_SEQ");
        modelBuilder.HasSequence("DEPOSITS_SEQ");
        modelBuilder.HasSequence("DISBURSEMENT_REQUEST_TB_SEQ");
        modelBuilder.HasSequence("EXCEL_CUSTOMERS_BENEFICIARIES_SEQ");
        modelBuilder.HasSequence("EXTERNAL_DEPOSIT_SETTINGS_SEQ");
        modelBuilder.HasSequence("EXTERNAL_DEPOSITS_SEQ");
        modelBuilder.HasSequence("FINANCIAL_CEILINGS_TB_SEQ");
        modelBuilder.HasSequence("FLOATING_INTEREST_PRICES_SEQ");
        modelBuilder.HasSequence("FUND_COLLECTION_CHECKS_TB_SEQ");
        modelBuilder.HasSequence("FUND_COMMENTS_TB_SEQ");
        modelBuilder.HasSequence("FUND_FILE_NUM_SEQ");
        modelBuilder.HasSequence("FUND_GROUP_ID_SEQ");
        modelBuilder.HasSequence("FUND_GUARANTEE_NOTES_SEQ");
        modelBuilder.HasSequence("FUND_GUARANTEE_SALARIES_SEQ");
        modelBuilder.HasSequence("FUND_GUARANTEES_EVALUATION_SEQ");
        modelBuilder.HasSequence("FUND_GUARANTEES_TB_SEQ");
        modelBuilder.HasSequence("FUND_INSTALLMENT_MOVEMENTS_TB_SEQ");
        modelBuilder.HasSequence("FUND_INSTALLMENT_PAYS_TB_SEQ");
        modelBuilder.HasSequence("FUND_INSTALLMENT_RESTRUCTURING_SEQ");
        modelBuilder.HasSequence("FUND_NON_MONETARY_POSTS_TB_SEQ");
        modelBuilder.HasSequence("FUND_PAYMENT_SEQUENCE");
        modelBuilder.HasSequence("FUND_PROCEDURE_TRANS_TB_SEQ");
        modelBuilder.HasSequence("FUND_ROLES_USERS_TRANS_TB_SEQ");
        modelBuilder.HasSequence("FUND_SETTING_SEQ");
        modelBuilder.HasSequence("FUND_SOURCE_CUST_CONTR_DESC_SEQ");
        modelBuilder.HasSequence("FUND_STATUS_TRANS_TB_SEQ");
        modelBuilder.HasSequence("FUND_TRANS_TB_SEQ");
        modelBuilder.HasSequence("FUND_VENDOR_SEQ");
        modelBuilder.HasSequence("FUNDS_TB_SEQ");
        modelBuilder.HasSequence("GROUP_PERMS_SEQ");
        modelBuilder.HasSequence("GROUP_SEQ");
        modelBuilder.HasSequence("GROUP_TRANSFER_CEILINGS_SEQ");
        modelBuilder.HasSequence("GUARANTORS_TB_SEQ");
        modelBuilder.HasSequence("HIS_CURRENCIES_TB_SEQ");
        modelBuilder.HasSequence("HIS_FUND_GUARANTEES_TB_SEQ");
        modelBuilder.HasSequence("HIS_RESERVATION_ACCOUNT_BALANCES_SEQ");
        modelBuilder.HasSequence("INSURANCE_COMPANIES_TB_SEQ");
        modelBuilder.HasSequence("LIQUIDATED_GURANTEES_TB_ID_SEQ");
        modelBuilder.HasSequence("LIQUIDATED_GURANTEES_TB_SEQ");
        modelBuilder.HasSequence("LOG_TABLES_SEQ");
        modelBuilder.HasSequence("LOGS_SEQ");
        modelBuilder.HasSequence("MAKER_CHECKER_REQUESTS_SEQ");
        modelBuilder.HasSequence("MASTER_SIGNATURES_SEQ");
        modelBuilder.HasSequence("MINERAL_GUESSERS_TB_SEQ");
        modelBuilder.HasSequence("MINERALS_GUARANTEE_TB_SEQ");
        modelBuilder.HasSequence("NON_MONETARY_POST_TYPES_TB_SEQ");
        modelBuilder.HasSequence("OFFICIAL_HOLIDAYS_SEQ");
        modelBuilder.HasSequence("PERMISSIBLE_MASTER_TB_SEQ");
        modelBuilder.HasSequence("PERMISSION_GROUPS_TB_SEQ");
        modelBuilder.HasSequence("PMA_SEQ");
        modelBuilder.HasSequence("PRODUCT_ADDED_FIELDS_TB_SEQ");
        modelBuilder.HasSequence("PRODUCT_FEES_TB_SEQ");
        modelBuilder.HasSequence("PROFILE_ACKNOWLEDGMENT_SEQ");
        modelBuilder.HasSequence("PROFILE_ADDRESS_SEQ");
        modelBuilder.HasSequence("PROFILE_BLACK_LISTS_SEQ");
        modelBuilder.HasSequence("PROFILE_BOARD_MEMBERS_SEQ");
        modelBuilder.HasSequence("PROFILE_BUY_SELL_POLICY_SEQ");
        modelBuilder.HasSequence("PROFILE_CLIENTS_SUPPLIERS_SEQ");
        modelBuilder.HasSequence("PROFILE_COMPANY_ACTIVITY_SEQ");
        modelBuilder.HasSequence("PROFILE_COMPETITORS_SEQ");
        modelBuilder.HasSequence("PROFILE_CONTACT_DTS_SEQ");
        modelBuilder.HasSequence("PROFILE_EMPLOYEE_CONTACTS_SEQ");
        modelBuilder.HasSequence("PROFILE_EMPLOYEES_SEQ");
        modelBuilder.HasSequence("PROFILE_EMPLOYEES_TB_SEQ");
        modelBuilder.HasSequence("PROFILE_EXECUTIVE_MEMBERS_SEQ");
        modelBuilder.HasSequence("PROFILE_EXPENSES_SEQ");
        modelBuilder.HasSequence("PROFILE_INCOMES_SEQ");
        modelBuilder.HasSequence("PROFILE_POLITICAL_OWNER_SEQ");
        modelBuilder.HasSequence("PROFILE_POLITICAL_RELATIVE_SEQ");
        modelBuilder.HasSequence("PROFILE_RELATED_COMPANIES_SEQ");
        modelBuilder.HasSequence("PROFILE_SIGNATURES_SEQ");
        modelBuilder.HasSequence("PROFILE_WORKS_SEQ");
        modelBuilder.HasSequence("PROFILES_CHANGES_TB_SEQ");
        modelBuilder.HasSequence("PROFILES_PARTNERS_SEQ");
        modelBuilder.HasSequence("PROFILES_SEQ");
        modelBuilder.HasSequence("PROJECT_EXPENSES_SEQ");
        modelBuilder.HasSequence("PROJECT_INVESTEMENTS_SEQ");
        modelBuilder.HasSequence("PROJECT_PARTNERS_MANAGERS_SEQ");
        modelBuilder.HasSequence("PROJECT_REVENUES_SEQ");
        modelBuilder.HasSequence("PROJECT_SEQ");
        modelBuilder.HasSequence("REAL_ESTATES_GUARANTEE_TB_SEQ");
        modelBuilder.HasSequence("REAL_ESTATES_GUESSERS_TB_SEQ");
        modelBuilder.HasSequence("S_GROUPS_SEQ");
        modelBuilder.HasSequence("S_USERS_SEQ");
        modelBuilder.HasSequence("SAVING_ACCOUNT_PENALTIES_SEQ");
        modelBuilder.HasSequence("SEQ_PROFILES_ID");
        modelBuilder.HasSequence("SIGNATURES_DETAILS_SEQ");
        modelBuilder.HasSequence("TEMP_FINANCIAL_CEILINGS_TB_SEQ");
        modelBuilder.HasSequence("TEMP_PASSWORD_SETTINGS_TB_SEQ");
        modelBuilder.HasSequence("TEST_SEQ");
        modelBuilder.HasSequence("TMP_ACCOUNT_CLOSING_SETTINGS_SEQ");
        modelBuilder.HasSequence("TMP_ACCOUNT_DEADLOCK_SETTINGS_SEQ");
        modelBuilder.HasSequence("TMP_ACTIVITY_SELL_METHODS_SEQ");
        modelBuilder.HasSequence("TMP_BIND_DEPOSIT_SETTINGS_SEQ");
        modelBuilder.HasSequence("TMP_C_COMMISSION_TYPE_CEIL_SEQ");
        modelBuilder.HasSequence("TMP_C_COMMISSION_TYPE_CURR_SEQ");
        modelBuilder.HasSequence("TMP_C_COMMISSION_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("TMP_C_DEPOSIT_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("TMP_C_DEPOSIT_TYPE_PERIODS_SEQ");
        modelBuilder.HasSequence("TMP_C_DEPOSIT_TYPES_SEQ");
        modelBuilder.HasSequence("TMP_C_GUARANTEE_TYPES_SEQ");
        modelBuilder.HasSequence("TMP_C_PRODUCT_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("TMP_C_PRODUCT_TYPES_TB_SEQ");
        modelBuilder.HasSequence("TMP_C_SAVING_ACC_INTERESTS_SEQ");
        modelBuilder.HasSequence("TMP_CRM_TICKETS_SEQ");
        modelBuilder.HasSequence("TMP_CURRENCY_SETTINGS_TB_SEQ");
        modelBuilder.HasSequence("TMP_CUST_COMM_TYPE_CEIL_SEQ");
        modelBuilder.HasSequence("TMP_CUST_COMM_TYPE_CURR_SEQ");
        modelBuilder.HasSequence("TMP_CUST_COMM_TYPE_DTS_SEQ");
        modelBuilder.HasSequence("TMP_CUST_DEPOSIT_TYPES_SEQ");
        modelBuilder.HasSequence("TMP_CUSTOMERS_CEILING_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATES_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATION_GROUP_ACC_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATION_GROUP_DELEG_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATION_GROUP_TRANS_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATION_GROUPS_SEQ");
        modelBuilder.HasSequence("TMP_DELEGATION_PERSON_TRAN_SEQ");
        modelBuilder.HasSequence("TMP_DEPOSITS_SEQ");
        modelBuilder.HasSequence("TMP_EXTER_DEPOSIT_SETTINGS_SEQ");
        modelBuilder.HasSequence("TMP_EXTERNAL_DEPOSITS_SEQ");
        modelBuilder.HasSequence("TMP_FUND_GUARANTEE_TB_SEQ");
        modelBuilder.HasSequence("TMP_FUND_GUARANTEES_TB_SEQ");
        modelBuilder.HasSequence("TMP_LIQUIDATED_GURANTEES_TB_SEQ");
        modelBuilder.HasSequence("TMP_OFFICIAL_HOLIDAYS_SEQ");
        modelBuilder.HasSequence("TMP_PERMISSION_GROUPS_TB_SEQ");
        modelBuilder.HasSequence("TMP_PRODUCT_EARLY_PAID_COMMISSION_SEQ");
        modelBuilder.HasSequence("TMP_PROF_CLIENT_SUPPLIER_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_ACKNOWLEDGMENT_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_BLACK_LISTS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_BOARD_MEMBERS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_BUY_SELL_POLIC_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_COMPETITORS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_CONTACT_DTS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_EXECUT_MEMBERS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_FIRM_ACTIVITY_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_PARTNERS_SEQ");
        modelBuilder.HasSequence("TMP_PROFILE_SIGNATURES_SEQ");
        modelBuilder.HasSequence("TMP_PROFILES_SEQ");
        modelBuilder.HasSequence("TMP_RESERVATION_ACCOUNT_TYPES_SEQ");
        modelBuilder.HasSequence("TMP_SCREEN_COMM_STEP_ROLES_SEQ");
        modelBuilder.HasSequence("TMP_SCREEN_COMMAND_STEPS_SEQ");
        modelBuilder.HasSequence("TMP_SCREEN_COMMAND_TABLES_SEQ");
        modelBuilder.HasSequence("TMP_WORKING_HOURS_TB_SEQ");
        modelBuilder.HasSequence("USER_GROUPS_SEQ");
        modelBuilder.HasSequence("USER_PERMS_SEQ");
        modelBuilder.HasSequence("USER_SEQ");
        modelBuilder.HasSequence("VEHICLES_GUARANTEE_TB_SEQ");
        modelBuilder.HasSequence("VENDORS_TB_SEQ");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}